#!/bin/bash
set -euo pipefail
# autonomous-toggle.sh — Enable or disable autonomous permissions
# for a project.
#
# Usage:
#   autonomous-toggle.sh on  [project-dir]
#   autonomous-toggle.sh off [project-dir]
#
# "on"  copies autonomous-settings.json into .claude/settings.json
#        (backs up any existing settings first)
# "off" restores the backup, or removes the settings file

ACTION="${1:-}"
PROJECT_DIR="${2:-.}"
SETTINGS_DIR="$PROJECT_DIR/.claude"
SETTINGS_FILE="$SETTINGS_DIR/settings.json"
BACKUP_FILE="$SETTINGS_DIR/settings.pre-autonomous.json"
PROJECT_AUTONOMOUS="$SETTINGS_DIR/settings.autonomous.json"
GLOBAL_TEMPLATE="$HOME/.claude/templates/autonomous-settings.json"

if [[ -z "$ACTION" ]]; then
    echo "Usage: autonomous-toggle.sh on|off [project-dir]"
    exit 1
fi

case "$ACTION" in
    on)
        # Prefer project-specific settings (generated by /plan-mission),
        # fall back to global template
        if [[ -f "$PROJECT_AUTONOMOUS" ]]; then
            SOURCE="$PROJECT_AUTONOMOUS"
            echo "Using project-specific autonomous settings"
        elif [[ -f "$GLOBAL_TEMPLATE" ]]; then
            SOURCE="$GLOBAL_TEMPLATE"
            echo "Using global autonomous template"
        else
            echo "No autonomous settings found (checked $PROJECT_AUTONOMOUS and $GLOBAL_TEMPLATE)"
            exit 1
        fi

        mkdir -p "$SETTINGS_DIR"

        # Backup existing settings if present
        if [[ -f "$SETTINGS_FILE" ]]; then
            cp "$SETTINGS_FILE" "$BACKUP_FILE"
            echo "Backed up existing settings to $BACKUP_FILE"
        fi

        cp "$SOURCE" "$SETTINGS_FILE"
        echo "Autonomous permissions enabled in $SETTINGS_FILE"

        # Ensure .claude/ is gitignored
        GITIGNORE="$PROJECT_DIR/.gitignore"
        if [[ ! -f "$GITIGNORE" ]]; then
            echo '.claude/' > "$GITIGNORE"
            echo "Created .gitignore with .claude/"
        elif ! grep -q '\.claude/' "$GITIGNORE" 2>/dev/null; then
            echo '.claude/' >> "$GITIGNORE"
            echo "Added .claude/ to .gitignore"
        fi
        ;;
    off)
        if [[ -f "$BACKUP_FILE" ]]; then
            mv "$BACKUP_FILE" "$SETTINGS_FILE"
            echo "Restored pre-autonomous settings"
        elif [[ -f "$SETTINGS_FILE" ]]; then
            rm "$SETTINGS_FILE"
            echo "Removed autonomous settings (no backup to restore)"
        else
            echo "No settings file found — already off"
        fi
        ;;
    *)
        echo "Unknown action: $ACTION (use 'on' or 'off')"
        exit 1
        ;;
esac
