#!/bin/bash
set -euo pipefail
# autonomous-toggle.sh — Enable or disable autonomous permissions
# for a project.
#
# Usage:
#   autonomous-toggle.sh on  [project-dir]
#   autonomous-toggle.sh off [project-dir]
#
# "on"  copies autonomous-settings.json into .claude/settings.json
#        (backs up any existing settings first)
# "off" restores the backup, or removes the settings file

ACTION="${1:-}"
PROJECT_DIR="${2:-.}"
SETTINGS_DIR="$PROJECT_DIR/.claude"
SETTINGS_FILE="$SETTINGS_DIR/settings.json"
BACKUP_FILE="$SETTINGS_DIR/settings.pre-autonomous.json"
PROJECT_AUTONOMOUS="$SETTINGS_DIR/settings.autonomous.json"
GLOBAL_TEMPLATE="$HOME/.claude/templates/autonomous-settings.json"

if [[ -z "$ACTION" ]]; then
    echo "Usage: autonomous-toggle.sh on|off [project-dir]"
    exit 1
fi

case "$ACTION" in
    on)
        # Prefer project-specific settings (generated by /plan-mission),
        # fall back to global template
        if [[ -f "$PROJECT_AUTONOMOUS" ]]; then
            SOURCE="$PROJECT_AUTONOMOUS"
            echo "Using project-specific autonomous settings"
        elif [[ -f "$GLOBAL_TEMPLATE" ]]; then
            SOURCE="$GLOBAL_TEMPLATE"
            echo "Using global autonomous template"
        else
            echo "No autonomous settings found (checked $PROJECT_AUTONOMOUS and $GLOBAL_TEMPLATE)"
            exit 1
        fi

        # Guard: if settings already match the source, toggle is already on
        if cmp -s "$SETTINGS_FILE" "$SOURCE"; then
            echo "Already in autonomous mode"
            exit 0
        fi

        mkdir -p "$SETTINGS_DIR"

        # Backup existing settings if present
        if [[ -f "$SETTINGS_FILE" ]]; then
            cp "$SETTINGS_FILE" "$BACKUP_FILE"
            echo "Backed up existing settings to $BACKUP_FILE"
        fi

        cp "$SOURCE" "$SETTINGS_FILE"
        echo "Autonomous permissions enabled in $SETTINGS_FILE"

        # Verify .claude/ is actually ignored. Appending to .gitignore does
        # not untrack an already-tracked file, so a bare grep-and-append can
        # report success while git keeps reporting the file dirty forever.
        # Ask git, and say so plainly when the answer is "still tracked".
        GITIGNORE="$PROJECT_DIR/.gitignore"
        if ! grep -qF '.claude/' "$GITIGNORE" 2>/dev/null; then
            echo '.claude/' >> "$GITIGNORE"
            echo "Added .claude/ to .gitignore"
        fi
        if git -C "$PROJECT_DIR" rev-parse --git-dir >/dev/null 2>&1; then
            if git -C "$PROJECT_DIR" ls-files --error-unmatch .claude/ >/dev/null 2>&1; then
                echo "WARNING: .claude/ is listed in .gitignore but still TRACKED." >&2
                echo "         The ignore has no effect until you run:" >&2
                echo "           git -C \"$PROJECT_DIR\" rm --cached -r .claude/" >&2
            fi
        fi
        ;;
    off)
        # on-call: if a restore fails, settings.json is left exactly as it was
        # and the backup is still on disk at $BACKUP_FILE — recover by hand
        # with `cp "$BACKUP_FILE" "$SETTINGS_FILE"`. Never delete either file
        # to "clean up": losing the pre-autonomous profile is how an elevated
        # profile survives a mission. Runbook: hooks/README or this comment.
        if [[ -f "$BACKUP_FILE" ]]; then
            # cp, not mv — the backup must survive until the restore is
            # verified, so a second `off` is a no-op rather than a deletion.
            if ! cp "$BACKUP_FILE" "$SETTINGS_FILE"; then
                echo "ERROR: failed to restore $SETTINGS_FILE from $BACKUP_FILE" >&2
                echo "Backup is intact. Settings left untouched." >&2
                exit 1
            fi
            if ! cmp -s "$BACKUP_FILE" "$SETTINGS_FILE"; then
                echo "ERROR: restore verification failed — $SETTINGS_FILE does not match the backup" >&2
                echo "Backup retained at $BACKUP_FILE. Resolve by hand." >&2
                exit 1
            fi
            rm -f "$BACKUP_FILE"
            echo "Restored pre-autonomous settings"
        elif [[ -f "$SETTINGS_FILE" ]]; then
            # No backup: either `off` already ran, or `on` was never used here.
            # Deleting the settings file is never the right answer — it would
            # destroy a profile this script did not create.
            if cmp -s "$SETTINGS_FILE" "$PROJECT_AUTONOMOUS" || cmp -s "$SETTINGS_FILE" "$GLOBAL_TEMPLATE"; then
                echo "ERROR: $SETTINGS_FILE still holds the autonomous profile, but no backup exists at $BACKUP_FILE." >&2
                echo "Not deleting it. Restore the intended profile by hand, or remove the file deliberately." >&2
                exit 1
            fi
            echo "No backup found; $SETTINGS_FILE is not the autonomous profile — already off"
        else
            echo "No settings file found — already off"
        fi
        ;;
    *)
        echo "Unknown action: $ACTION (use 'on' or 'off')"
        exit 1
        ;;
esac
